// flow-typed signature: 5a892ea6b3ee622cd3d19f11240bd72f
// flow-typed version: <<STUB>>/aurora-utilities_v^1.0.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurora-utilities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurora-utilities' {
  declare module.exports: any;
}
