// flow-typed signature: cde2d8f658ba62a5cc15c925f89d786a
// flow-typed version: <<STUB>>/onchange_v^3.3.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'onchange'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'onchange' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'onchange/cli' {
  declare module.exports: any;
}

declare module 'onchange/echo' {
  declare module.exports: any;
}

declare module 'onchange/test/index' {
  declare module.exports: any;
}

declare module 'onchange/test/slow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'onchange/cli.js' {
  declare module.exports: $Exports<'onchange/cli'>;
}
declare module 'onchange/echo.js' {
  declare module.exports: $Exports<'onchange/echo'>;
}
declare module 'onchange/index' {
  declare module.exports: $Exports<'onchange'>;
}
declare module 'onchange/index.js' {
  declare module.exports: $Exports<'onchange'>;
}
declare module 'onchange/test/index.js' {
  declare module.exports: $Exports<'onchange/test/index'>;
}
declare module 'onchange/test/slow.js' {
  declare module.exports: $Exports<'onchange/test/slow'>;
}
